<a href="https://colab.research.google.com/github/Vakhranev/RNIMU_Pirogova/blob/main/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_numpy_%D0%B4%D0%BB%D1%8F_%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2_%D0%B8_%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.arange(3.0)

array([0., 1., 2.])

In [5]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [6]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [7]:
X, Y = np.meshgrid([1,2,3], [4,5,7])
X

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
Y

array([[4, 4, 4],
       [5, 5, 5],
       [7, 7, 7]])

In [9]:
np.mgrid[0:5:3j,0:5:3j]

array([[[0. , 0. , 0. ],
        [2.5, 2.5, 2.5],
        [5. , 5. , 5. ]],

       [[0. , 2.5, 5. ],
        [0. , 2.5, 5. ],
        [0. , 2.5, 5. ]]])

In [11]:
np.ogrid[0:5,0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

In [12]:
np.empty([2, 2], dtype=int)

array([[4616189618054758400, 4617360198398210699],
       [4618835037213519420, 4620693217682128896]])

In [13]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [16]:
np.tril([[1,2,3],[4,5,6],[7,8,9], [10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [17]:
np.triu([[1,2,3],[4,5,6],[7,8,9], [10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [19]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])